# Site settings
title: Your awesome title
email: your-email@example.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/kotlin-ref"
url: "https://vakho10.github.io"
github_username: vakho10

# Build settings
remote_theme: sighingnow/jekyll-gitbook
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# jekyll-gitbook settings
toc:
  enabled: true
  h_min: 1
  h_max: 3

syntax_highlighter_style: colorful

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
